**(1)** Load the array you saved in the previous lesson from the disk.

In [48]:
import csv
import numpy as np
array=np.load('array.npy')

In [49]:
array

array([[ 1.    ,  1.    ,  1.    ,  1.    ,  1.    ],
       [ 0.    , 37.4341, 35.852 ,  7.02  ,  4.1   ],
       [ 0.    , 37.6878, 37.4016, 10.27  ,  4.4   ],
       [ 0.    , 37.2003, 30.4376, 78.07  ,  4.    ],
       [ 0.    , 35.6846, 26.7266, 42.77  ,  4.5   ],
       [ 0.    , 36.4171, 28.6991, 14.86  ,  4.1   ],
       [ 0.    , 36.0535, 31.2135, 36.68  ,  5.2   ],
       [ 0.    , 37.1958, 30.6241, 50.33  ,  4.8   ],
       [ 0.    , 36.9653, 27.7633,  6.93  ,  4.3   ],
       [ 0.    , 38.893 , 26.4483, 11.62  ,  4.2   ],
       [ 0.    , 37.3773, 36.3855, 10.53  ,  4.8   ],
       [ 0.    , 35.8861, 26.0695, 28.49  ,  4.9   ],
       [ 0.    , 37.4635, 36.3113, 15.29  ,  4.3   ],
       [ 0.    , 37.0201, 36.0845, 10.    ,  4.1   ],
       [ 0.    , 37.6546, 26.6698,  4.5   ,  4.5   ],
       [ 0.    , 37.5318, 29.848 , 17.58  ,  4.6   ],
       [ 0.    , 39.0388, 44.1533,  7.52  ,  4.5   ],
       [ 0.    , 38.357 , 44.8686, 10.05  ,  4.1   ],
       [ 0.    , 35.7018, 28

**(2)** Display the mean and the standard deviation for each column.

In [50]:
print(" Mean of each column :",array.mean(axis = 0))

 Mean of each column : [ 0.05     35.41254  31.105145 19.0195    4.23    ]


In [51]:
print("Standart deviation of each column :",array.std(axis = 0))

Standart deviation of each column : [ 0.21794495  7.94782002  8.83572219 18.73871326  0.80690768]


**(3)** Subtract 1, 25, 25, 10, 4 from columns in order. (Remember it can be subtracted in one line of code.)

In [52]:
for i in range(20):
  for j in range(5):
    target=[1,25,25,10,4]
    array[i][j]=np.round(np.subtract(array[i][j],target[j]))
array

array([[  0., -24., -24.,  -9.,  -3.],
       [ -1.,  12.,  11.,  -3.,   0.],
       [ -1.,  13.,  12.,   0.,   0.],
       [ -1.,  12.,   5.,  68.,   0.],
       [ -1.,  11.,   2.,  33.,   0.],
       [ -1.,  11.,   4.,   5.,   0.],
       [ -1.,  11.,   6.,  27.,   1.],
       [ -1.,  12.,   6.,  40.,   1.],
       [ -1.,  12.,   3.,  -3.,   0.],
       [ -1.,  14.,   1.,   2.,   0.],
       [ -1.,  12.,  11.,   1.,   1.],
       [ -1.,  11.,   1.,  18.,   1.],
       [ -1.,  12.,  11.,   5.,   0.],
       [ -1.,  12.,  11.,   0.,   0.],
       [ -1.,  13.,   2.,  -6.,   0.],
       [ -1.,  13.,   5.,   8.,   1.],
       [ -1.,  14.,  19.,  -2.,   0.],
       [ -1.,  13.,  20.,   0.,   0.],
       [ -1.,  11.,   3.,  -4.,   0.],
       [ -1.,  13.,  12.,   1.,   0.]])

**(4)** Multiply each element by 2. (Remember it can be multiplied in one line of code.)

In [53]:
array*2

array([[  0., -48., -48., -18.,  -6.],
       [ -2.,  24.,  22.,  -6.,   0.],
       [ -2.,  26.,  24.,   0.,   0.],
       [ -2.,  24.,  10., 136.,   0.],
       [ -2.,  22.,   4.,  66.,   0.],
       [ -2.,  22.,   8.,  10.,   0.],
       [ -2.,  22.,  12.,  54.,   2.],
       [ -2.,  24.,  12.,  80.,   2.],
       [ -2.,  24.,   6.,  -6.,   0.],
       [ -2.,  28.,   2.,   4.,   0.],
       [ -2.,  24.,  22.,   2.,   2.],
       [ -2.,  22.,   2.,  36.,   2.],
       [ -2.,  24.,  22.,  10.,   0.],
       [ -2.,  24.,  22.,   0.,   0.],
       [ -2.,  26.,   4., -12.,   0.],
       [ -2.,  26.,  10.,  16.,   2.],
       [ -2.,  28.,  38.,  -4.,   0.],
       [ -2.,  26.,  40.,   0.,   0.],
       [ -2.,  22.,   6.,  -8.,   0.],
       [ -2.,  26.,  24.,   2.,   0.]])